// Clerk's SignIn/SignUp (page and modal) in the site style (F34, #77): the :root palette,
// Pixelify for headings and buttons, and the existing recipes (`.px-btn`, `.px-frame`) on
// Clerk's elements. Clerk's own CSS goes into the `clerk` layer (declared in app/globals.css),
// so Tailwind utilities and our unlayered recipes win over it. Colours are the :root values
// because Clerk derives shades from them and can't read CSS variables.
export const clerkAppearance = {
  cssLayerName: "clerk",
  variables: {
    colorPrimary: "#ffd84d",
    colorPrimaryForeground: "#1a1405",
    colorBackground: "#141a33",
    colorForeground: "#eef2ff",
    colorMutedForeground: "#9aa6c8",
    colorMuted: "#1b2242",
    colorInput: "#0f1326",
    colorInputForeground: "#eef2ff",
    colorBorder: "#2a3358",
    colorNeutral: "#eef2ff",
    colorDanger: "#ff5c5c",
    colorSuccess: "#3ddc97",
    colorWarning: "#ff9f43",
    colorRing: "#4de3ff",
    colorShadow: "#05070f",
    colorModalBackdrop: "rgba(5, 7, 15, 0.72)",
    fontFamily: "var(--f-body)",
    fontFamilyButtons: "var(--f-display)",
    borderRadius: "6px",
  },
  elements: {
    cardBox: "px-frame !rounded-none",
    card: "!rounded-none",
    footer: "!rounded-none",
    headerTitle: "!font-display !text-2xl !tracking-wide",
    headerSubtitle: "!text-muted",
    formButtonPrimary: "px-btn !h-11 !rounded-none !text-[15px]",
    socialButtonsBlockButton: "px-btn !h-10 !rounded-none",
    socialButtonsBlockButtonText: "!font-display",
    formFieldInput: "!rounded-none",
    dividerLine: "!bg-border-strong",
    footerActionLink: "!text-signal hover:!text-primary",
    identityPreviewEditButton: "!text-signal",
    formResendCodeLink: "!text-signal",
  },
} as const;
