// Sixteen self-drawn 16×16 pixel avatars (overnight-decisions Q17). Pure data.
// Each grid row is 16 characters; "." is transparent; keys map through the avatar's palette.
import type { SpritePalette, SpriteRows } from "./PixelSprite";

export type AvatarDef = { id: string; name: string; bg: string; rows: SpriteRows; palette: SpritePalette };

const K = "#0b0e1d";
const W = "#ffffff";

export const AVATARS = [
  {
    id: "anglerfish",
    name: "Anglerfish",
    bg: "#16224a",
    palette: { b: "#4656a3", w: W, k: K, m: "#1a1030", t: W, l: "#7d8fdc", s: "#a3aed0", y: "#ffd84d", f: "#ff5d8f" },
    rows: [
      "..........y.....",
      ".........yyy....",
      "..........y.....",
      "...........s....",
      "......bbbbbs....",
      "....bbbbbbbbb...",
      "...bbwwbbbbbbb..",
      "..bbbwkbbbbbbbf.",
      ".mmmbbbbbbbbbbff",
      "mtmtmbbbbbbbbbff",
      "mmmmmlbbbbbbbbf.",
      "mtmtmllbbbbbbbf.",
      ".mmmmlllbbbbbb..",
      "...bblllllbbb...",
      ".....bbbbbb.....",
      "......f..f......",
    ],
  },
  {
    id: "axolotl",
    name: "Axolotl",
    bg: "#3a1838",
    palette: { p: "#ff9ccf", r: "#ff5d8f", k: K, w: W, c: "#ff6fae", m: "#8f2447", l: "#ffd0e8" },
    rows: [
      "................",
      "r..............r",
      ".r.pppppppppp.r.",
      "rrpppppppppppprr",
      ".pppppppppppppp.",
      "rppkkppppppkkppr",
      ".ppkwppppppkwpp.",
      "..pppppppppppp..",
      "..pppcppppcppp..",
      "...ppppmmpppp...",
      "....pppppppp....",
      "...pppllllppp...",
      "..ppplllllllpp..",
      "..pp.llllll.pp..",
      "....pp....pp....",
      "................",
    ],
  },
  {
    id: "astronaut",
    name: "Astronaut",
    bg: "#0d1030",
    palette: { w: "#e9edf6", b: "#1b2242", c: "#4de3ff", s: "#8d98b5", r: "#ff5d8f" },
    rows: [
      "................",
      ".....wwwwww.....",
      "...wwwwwwwwww...",
      "..wwbbbbbbbbww..",
      "..wbbcbbbbbbbw..",
      "..wbccbbbbbbbw..",
      "..wbbbbbbbbbbw..",
      "..wwbbbbbbbbww..",
      "...wwwwwwwwww...",
      "..ssswwwwwwsss..",
      ".sswwwwrrwwwwss.",
      ".swwwwwrrwwwwws.",
      ".ww.wwwwwwww.ww.",
      "....wwwwwwww....",
      "....www..www....",
      "....sss..sss....",
    ],
  },
  {
    id: "frog",
    name: "Frog",
    bg: "#123a2c",
    palette: { g: "#3ddc97", w: W, k: K, m: "#1f7a52", l: "#b8f5d9", r: "#ff9ccf" },
    rows: [
      "................",
      "..www......www..",
      ".wwkkw....wwkkw.",
      ".wwkkwggggwwkkw.",
      ".gwwwggggggwwwg.",
      ".gggggggggggggg.",
      "gggggggggggggggg",
      "gggrgggggggggrgg",
      "ggmggggggggggmgg",
      ".gmmmmmmmmmmmmg.",
      "..gggggggggggg..",
      "..glllllllllllg.",
      "..gllllllllllg..",
      "...gggg..gggg...",
      "..ggg......ggg..",
      "................",
    ],
  },
  {
    id: "cat",
    name: "Cat",
    bg: "#3a2414",
    palette: { o: "#ff9f43", g: "#3ddc97", k: K, p: "#ff5d8f", m: "#c46a1c", w: "#fff1e0" },
    rows: [
      "................",
      "..o..........o..",
      "..oo........oo..",
      "..ooo......ooo..",
      "..oooooooooooo..",
      ".oooooooooooooo.",
      ".ooggooooooggoo.",
      ".ookgoooooookgo.",
      ".oooooopooooooo.",
      ".oooooommoooooo.",
      "w.oooooooooooo.w",
      ".w.oooooooooo.w.",
      "...oowwwwwwoo...",
      "...owwwwwwwwo...",
      "...oo.oooo.oo...",
      "................",
    ],
  },
  {
    id: "robot",
    name: "Robot",
    bg: "#1a2236",
    palette: { s: "#8d98b5", S: "#5e6a8a", b: K, c: "#4de3ff", y: "#ffd84d", r: "#ff5c5c", g: "#3ddc97", k: "#2a3358" },
    rows: [
      ".......r........",
      ".......s........",
      "....ssssssss....",
      "...ssssssssss...",
      "...sbbbbbbbbs...",
      "...sbcbbbbcbs...",
      "...sbccbbccbs...",
      "...sbbbbbbbbs...",
      "...sbbyyyybbs...",
      "...ssssssssss...",
      "....ssssssss....",
      "..ssSSSSSSSSss..",
      "..s.SyrSSgyS.s..",
      "..s.SSSSSSSS.s..",
      "....SS....SS....",
      "....kk....kk....",
    ],
  },
  {
    id: "octopus",
    name: "Octopus",
    bg: "#221846",
    palette: { v: "#9d7bff", l: "#c9b5ff", w: W, k: K, m: "#5b3fbf" },
    rows: [
      "................",
      ".....vvvvvv.....",
      "...vvvvvvvvvv...",
      "..vvvvvvvvvvvv..",
      "..vvwwvvvvwwvv..",
      "..vvwkvvvvwkvv..",
      "..vvvvvvvvvvvv..",
      "..vvvvvmmvvvvv..",
      "...vvvvvvvvvv...",
      "..vvvvvvvvvvvv..",
      ".vvlvvlvvlvvlvv.",
      ".v.vv.vv.vv.vv.v",
      "vv.v..v..v..v.vv",
      "................",
      "................",
      "................",
    ],
  },
  {
    id: "penguin",
    name: "Penguin",
    bg: "#14304a",
    palette: { k: "#1b2242", w: "#eef2ff", o: "#ff9f43" },
    rows: [
      "................",
      ".....kkkkkk.....",
      "....kkkkkkkk....",
      "...kkwwwwwwkk...",
      "...kwkwwwwkwk...",
      "...kwwwwwwwwk...",
      "...kwwwooowwk...",
      "..kkkwwwowwkkk..",
      ".kkkwwwwwwwwkkk.",
      ".kk.wwwwwwww.kk.",
      ".k..wwwwwwww..k.",
      "....wwwwwwww....",
      "....kwwwwwwk....",
      ".....kkkkkk.....",
      "....oo....oo....",
      "................",
    ],
  },
  {
    id: "fox",
    name: "Fox",
    bg: "#3a1c10",
    palette: { o: "#ff8a3d", w: "#fff1e0", k: K },
    rows: [
      "................",
      ".o............o.",
      ".oo..........oo.",
      ".owo........owo.",
      ".owoooooooooowo.",
      ".oooooooooooooo.",
      ".ookooooooookoo.",
      ".oooooooooooooo.",
      "..wwooooooooww..",
      "...wwwwkkwwww...",
      "....wwwwwwww....",
      ".....wwwwww.....",
      "....oooooooo....",
      "...oooooooooo...",
      "...oo.oooo.oo...",
      "................",
    ],
  },
  {
    id: "ghost",
    name: "Ghost",
    bg: "#24204a",
    palette: { w: "#dfe6ff", k: "#1b2242", p: "#ff9ccf" },
    rows: [
      "................",
      ".....wwwwww.....",
      "...wwwwwwwwww...",
      "..wwwwwwwwwwww..",
      "..wwkkwwwwkkww..",
      "..wwkkwwwwkkww..",
      "..wwwwwwwwwwww..",
      "..wwwwpwwpwwww..",
      "..wwwwwkkwwwww..",
      "..wwwwwwwwwwww..",
      "..wwwwwwwwwwww..",
      "..wwwwwwwwwwww..",
      "..wwwwwwwwwwww..",
      "..ww.www.www.w..",
      "..w...w...w.....",
      "................",
    ],
  },
  {
    id: "slime",
    name: "Slime",
    bg: "#10302a",
    palette: { g: "#7bf5a4", G: "#3ddc97", w: W, k: K, m: "#1f7a52" },
    rows: [
      "................",
      "................",
      "................",
      "......gggg......",
      "....gggggggg....",
      "...ggwgggggggg..",
      "..ggwwggggggggg.",
      "..gggkggggkgggg.",
      ".ggggkggggkggggg",
      ".gggggggggggggg.",
      ".ggggggmmgggggg.",
      "gggggggggggggggg",
      "gGGGGGGGGGGGGGGg",
      ".GGGGGGGGGGGGGG.",
      "................",
      "................",
    ],
  },
  {
    id: "owl",
    name: "Owl",
    bg: "#2a1c14",
    palette: { b: "#8a5a3a", w: "#fff1e0", k: K, y: "#ffd84d", l: "#d9b38c" },
    rows: [
      "................",
      "..b..........b..",
      "..bb........bb..",
      "..bbbbbbbbbbbb..",
      ".bbwwwbbbbwwwbb.",
      ".bwwkwwbbwwkwwb.",
      ".bwwwwwbbwwwwwb.",
      ".bbwwwbyybwwwbb.",
      ".bbbbbbyybbbbbb.",
      ".bbllllllllllbb.",
      ".bbllllllllllbb.",
      "..bllllllllllb..",
      "..bbllllllllbb..",
      "...bbbbbbbbbb...",
      "....yy....yy....",
      "................",
    ],
  },
  {
    id: "bear",
    name: "Bear",
    bg: "#2e1c12",
    palette: { b: "#9a5a2a", n: "#e0b48a", k: K, m: "#ff5d8f" },
    rows: [
      "................",
      "..bb........bb..",
      ".bnnb......bnnb.",
      ".bnbbbbbbbbbbnb.",
      "..bbbbbbbbbbbb..",
      ".bbbbbbbbbbbbbb.",
      ".bbbkbbbbbbkbbb.",
      ".bbbbbbbbbbbbbb.",
      ".bbbbnnnnnnbbbb.",
      ".bbbnnnkknnnbbb.",
      "..bbbnnmmnnbbb..",
      "...bbbbbbbbbb...",
      "..bbbbbbbbbbbb..",
      "..bb.bbbbbb.bb..",
      "................",
      "................",
    ],
  },
  {
    id: "alien",
    name: "Alien",
    bg: "#1c2a10",
    palette: { g: "#a6f04d", k: K, w: W, m: "#4a7a1a", v: "#9d7bff" },
    rows: [
      "................",
      "......g..g......",
      ".......gg.......",
      ".....gggggg.....",
      "...gggggggggg...",
      "..gggggggggggg..",
      "..gkkkggggkkkg..",
      "..gkwkggggkwkg..",
      "..ggkkggggkkgg..",
      "...gggggggggg...",
      "....gggmmggg....",
      ".....gggggg.....",
      "....vvvvvvvv....",
      "...vvvvvvvvvv...",
      "...vv.vvvv.vv...",
      "................",
    ],
  },
  {
    id: "crab",
    name: "Crab",
    bg: "#3a1414",
    palette: { r: "#ff5c5c", R: "#c43a3a", w: W, k: K, m: "#8f2020" },
    rows: [
      "................",
      ".rr..........rr.",
      "rrrr........rrrr",
      "rr.r........r.rr",
      ".rrr..w..w..rrr.",
      "..r...k..k...r..",
      "...r..r..r..r...",
      "....rrrrrrrr....",
      "...rrrrrrrrrr...",
      "..rrrrrrrrrrrr..",
      "..rrrRmmmmRrrr..",
      "...rrrrrrrrrr...",
      "..r.r.r..r.r.r..",
      ".r..r......r..r.",
      "................",
      "................",
    ],
  },
  {
    id: "jellyfish",
    name: "Jellyfish",
    bg: "#102a3a",
    palette: { p: "#ff9ccf", l: W, k: K, m: "#8f2447", c: "#4de3ff" },
    rows: [
      "................",
      "................",
      ".....pppppp.....",
      "...pppppppppp...",
      "..pplppppppppp..",
      "..plpppppppppp..",
      "..ppkkppppkkpp..",
      "..pppppppppppp..",
      "..ppppmmmmpppp..",
      "..cccccccccccc..",
      "...c.c.cc.c.c...",
      "...c.c.cc.c.c...",
      "....c.c..c.c....",
      "...c...c..c..c..",
      "................",
      "................",
    ],
  },
] as const satisfies readonly AvatarDef[];

export type AvatarId = (typeof AVATARS)[number]["id"];
export const DEFAULT_AVATAR: AvatarId = "anglerfish";

export function avatarById(id: string | null | undefined): AvatarDef {
  return AVATARS.find((a) => a.id === id) ?? AVATARS[0];
}

/** A stable default avatar for a Player id (so new Players don't all look the same). */
export function defaultAvatarFor(seed: string): AvatarId {
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) | 0;
  return AVATARS[Math.abs(h) % AVATARS.length].id;
}
